package Nim;

import java.util.Random;

/**
 * Creates the Initial Screen of the Game
 * 
 * @author Nick Alexander
 * @version Nov 27, 2013
 */
public class OpeningInterface extends javax.swing.JFrame {
    public static GameInterface gameInterface;
    private boolean isTwoPlayer;
    
    /**
     * Creates new OpeningInterface
     */
    public OpeningInterface() {
        initComponents();
    }
    
    /**
     * Creates a New Game Object
     */
    public void createGame()
    {
        Random random = new Random();
        Game game = new Game(random.nextInt(2) + 1, this.isTwoPlayer);
        gameInterface = new GameInterface(game);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNim = new javax.swing.JLabel();
        btnPVC = new javax.swing.JButton();
        btnPVP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNim.setFont(new java.awt.Font("Alberta", 0, 50)); // NOI18N
        lblNim.setForeground(new java.awt.Color(0, 204, 0));
        lblNim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNim.setText("The Game of Nim!");

        btnPVC.setFont(new java.awt.Font("Alberta", 0, 24)); // NOI18N
        btnPVC.setForeground(new java.awt.Color(255, 0, 0));
        btnPVC.setText("<html>Player<br>Versus<br>Computer</html>");
        btnPVC.setPreferredSize(new java.awt.Dimension(200, 200));
        btnPVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPVCActionPerformed(evt);
            }
        });

        btnPVP.setFont(new java.awt.Font("Alberta", 0, 24)); // NOI18N
        btnPVP.setForeground(new java.awt.Color(0, 0, 255));
        btnPVP.setText("<html>Player<br>Versus<br>Player</html>");
        btnPVP.setPreferredSize(new java.awt.Dimension(200, 200));
        btnPVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPVPActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lblNim, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnPVP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnPVC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblNim, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnPVP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnPVC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles Click of the Player Versus Player Button
     * 
     * @param evt Button Click Event
     */
    private void btnPVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPVPActionPerformed
        this.isTwoPlayer = true;
        this.createGame();
        this.dispose();
    }//GEN-LAST:event_btnPVPActionPerformed

    /**
     * Handles Click of the Player Computer Player Button
     * 
     * @param evt Button Click Event
     */
    private void btnPVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPVCActionPerformed
        this.isTwoPlayer = false;
        this.createGame();
        this.dispose();
    }//GEN-LAST:event_btnPVCActionPerformed

    //<editor-fold desc="Variable Declarations" defaultstate="collapsed">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPVC;
    private javax.swing.JButton btnPVP;
    private javax.swing.JLabel lblNim;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
